### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by nemec** [mike-eason/earthporn_desktop#2]
Once the OSX pull request is merged, it should be easy to add support for Linux (Gnome, at least) with the following command. gsettings is basically the registry equivalent on certain variations of Linux.

    gsettings set org.gnome.desktop.background picture-uri file://" + saveLocation

**Comment by mike-eason** [comment]
Hello there,

Unfortunately I don't have a Linux machine at hand, do you mind implementing and testing? I've commited the skeleton class (commit 0f829707c1305fe61a0360d0e31915c1f8fd9b65), all that's required is the implementation.

**Comment by nemec** [comment]
Thanks, I'll try and fill that out soon.
